### ISSUE TITLE
Add programatically access to field value from helpers

### ISSUE THREAD

**Issue by gibson** [jonjamz/blaze-forms#65]
Please add programm access to set or get current value

**Comment by jonjamz** [comment]
Do you mean you'd like to access the form data context from the outside, like `form1.set('name','jon')`?

**Comment by gibson** [comment]
yes, i making element for users emails and id need to add new address-verified pairs to field without any form action - only render (no validation and no any action) from helpers

**Comment by jonjamz** [comment]
Check out #76 and the new functionality in `v2.1.0`. Is this what you're looking for?
